[package]
name = "quickjs-oxide-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
quickjs-oxide-core = { workspace = true }
quickjs-oxide-compiler = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }

[features]
default = []
test262-host = ["quickjs-oxide-core/test262-host"]
test-support = ["quickjs-oxide-core/test-support", "quickjs-oxide-compiler/test-support"]
[dev-dependencies]
quickjs-oxide-host = { workspace = true }
quickjs-oxide-core = { workspace = true, features = ["test-support"] }
quickjs-oxide-compiler = { workspace = true, features = ["test-support"] }
