"""Pinned data and expected shapes for surface."""

EXPECTED_ROOT_MODULES = ('atoms',
 'code',
 'function_envelope',
 'function_translate',
 'bytecode_image',
 'graph',
 'pinned_atoms',
 'pinned_opcodes',
 'read_cursor',
 'ordinary_leaf',
 'scalar_script',
 'wire')

EXPECTED_ORDINARY_FACADE_NAMES = {'DetachedAtomName',
 'DetachedPrimitive',
 'OrdinaryLeafApplyKind',
 'OrdinaryLeafBinaryOp',
 'OrdinaryLeafDraft',
 'OrdinaryLeafMetadataDraft',
 'OrdinaryLeafOp',
 'OrdinaryLeafPredicateOp',
 'OrdinaryLeafReadError',
 'OrdinaryLeafStackOp',
 'OrdinaryLeafUnaryOp',
 'RootFunctionConstantSelector',
 'decode_trusted_ordinary_leaf'}

EXPECTED_BINARY_VISIBLE_COUNTS = {'crates/engine/src/runtime/binary_object/atoms.rs': 16,
 'crates/engine/src/runtime/binary_object/bytecode_image/atoms.rs': 11,
 'crates/engine/src/runtime/binary_object/bytecode_image/budget.rs': 32,
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/function.rs': 8,
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/mod.rs': 10,
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/module.rs': 10,
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/emit.rs': 2,
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/mod.rs': 5,
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/plan/function.rs': 1,
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/plan/mod.rs': 10,
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/plan/module.rs': 2,
 'crates/engine/src/runtime/binary_object/bytecode_image/mod.rs': 6,
 'crates/engine/src/runtime/binary_object/bytecode_image/model.rs': 111,
 'crates/engine/src/runtime/binary_object/bytecode_image/native_plan.rs': 27,
 'crates/engine/src/runtime/binary_object/code.rs': 27,
 'crates/engine/src/runtime/binary_object/function_envelope/mod.rs': 2,
 'crates/engine/src/runtime/binary_object/function_envelope/model.rs': 117,
 'crates/engine/src/runtime/binary_object/function_envelope/prefix.rs': 11,
 'crates/engine/src/runtime/binary_object/function_translate/capability.rs': 10,
 'crates/engine/src/runtime/binary_object/function_translate/dto.rs': 41,
 'crates/engine/src/runtime/binary_object/function_translate/mod.rs': 6,
 'crates/engine/src/runtime/binary_object/graph/arena.rs': 19,
 'crates/engine/src/runtime/binary_object/graph/decode.rs': 28,
 'crates/engine/src/runtime/binary_object/graph/encode.rs': 4,
 'crates/engine/src/runtime/binary_object/graph/mod.rs': 6,
 'crates/engine/src/runtime/binary_object/graph/model.rs': 56,
 'crates/engine/src/runtime/binary_object/graph/sab_transport.rs': 38,
 'crates/engine/src/runtime/binary_object/graph/write_state.rs': 21,
 'crates/engine/src/runtime/binary_object/mod.rs': 2,
 'crates/engine/src/runtime/binary_object/ordinary_leaf.rs': 30,
 'crates/engine/src/runtime/binary_object/pinned_atoms.rs': 9,
 'crates/engine/src/runtime/binary_object/pinned_opcodes.rs': 23,
 'crates/engine/src/runtime/binary_object/read_cursor.rs': 2,
 'crates/engine/src/runtime/binary_object/scalar_script.rs': 6,
 'crates/engine/src/runtime/binary_object/wire.rs': 46}

EXPECTED_FIXTURE_VISIBLE_COUNTS = {'crates/engine/src/runtime/binary_object/bytecode_image/atoms.rs': 1,
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/mod.rs': 1,
 'crates/engine/src/runtime/binary_object/bytecode_image/mod.rs': 1,
 'crates/engine/src/runtime/binary_object/bytecode_image/model.rs': 2,
 'crates/engine/src/runtime/binary_object/bytecode_image/native_plan.rs': 27,
 'crates/engine/src/runtime/binary_object/graph/decode.rs': 1,
 'crates/engine/src/runtime/binary_object/graph/sab_transport.rs': 29,
 'crates/engine/src/runtime/binary_object/function_translate/capability.rs': 10,
 'crates/engine/src/runtime/binary_object/function_translate/dto.rs': 41,
 'crates/engine/src/runtime/binary_object/function_translate/mod.rs': 6,
 'crates/engine/src/runtime/binary_object/mod.rs': 2,
 'crates/engine/src/runtime/binary_object/ordinary_leaf.rs': 30,
 'crates/engine/src/runtime/binary_object/pinned_opcodes.rs': 23,
 'crates/engine/src/runtime/binary_object/read_cursor.rs': 2,
 'crates/engine/src/runtime/binary_object/scalar_script.rs': 6}

EXPECTED_BYTECODE_IMAGE_IMPL_HEADERS = {'crates/engine/src/runtime/binary_object/bytecode_image/atoms.rs': ['fmt::Display for ImageAtomError',
                                                       'std::error::Error for ImageAtomError',
                                                       'From<WireError> for ImageAtomError',
                                                       'ImageAtomTable'],
 'crates/engine/src/runtime/binary_object/bytecode_image/budget.rs': ['ModuleLimits',
                                                        'fmt::Display for ModuleBudgetError',
                                                        'std::error::Error for ModuleBudgetError',
                                                        'BytecodeImageLimits',
                                                        'fmt::Display for BytecodeImageBudgetError',
                                                        'std::error::Error for '
                                                        'BytecodeImageBudgetError',
                                                        'ModuleUsage',
                                                        'RemainingModuleBudget',
                                                        'ModuleTotals',
                                                        'FunctionUsage',
                                                        'RemainingFunctionBudget',
                                                        'FunctionTotals'],
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/function.rs': ['FunctionFrame', 'FunctionTable'],
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/mod.rs': ['fmt::Display for BytecodeImageError',
                                                            'std::error::Error for '
                                                            'BytecodeImageError',
                                                            'From<WireError> for '
                                                            'BytecodeImageError',
                                                            'From<ImageAtomError> for '
                                                            'BytecodeImageError',
                                                            'From<DecodeError<ImageOpaque>> for '
                                                            'BytecodeImageError',
                                                            'From<FunctionEnvelopeError> for '
                                                            'BytecodeImageError',
                                                            'From<ModuleBudgetError> for '
                                                            'BytecodeImageError',
                                                            'From<BytecodeImageBudgetError> for '
                                                            'BytecodeImageError',
                                                            'From<SabArchiveError> for '
                                                            'BytecodeImageError',
                                                            'AuthenticatedFunction',
                                                            'AuthenticatedModule'],
 'crates/engine/src/runtime/binary_object/bytecode_image/decode/module.rs': ['ModuleFrame', 'ModuleTable'],
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/mod.rs': ['BytecodeImageEncodeOptions',
                                                            'fmt::Display for '
                                                            'BytecodeImageEncodeError',
                                                            'std::error::Error for '
                                                            'BytecodeImageEncodeError',
                                                            'From<WireError> for '
                                                            'BytecodeImageEncodeError',
                                                            'From<GraphError> for '
                                                            'BytecodeImageEncodeError',
                                                            'From<DataWriteStateError> for '
                                                            'BytecodeImageEncodeError',
                                                            'From<BytecodeImageBudgetError> for '
                                                            'BytecodeImageEncodeError',
                                                            'From<ModuleBudgetError> for '
                                                            'BytecodeImageEncodeError',
                                                            'From<FunctionEnvelopeError> for '
                                                            'BytecodeImageEncodeError',
                                                            'From<CodeError> for '
                                                            'BytecodeImageEncodeError'],
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/plan/function.rs': ["<'a> PlanBuilder<'a>"],
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/plan/mod.rs': ["<'a> PlanBuilder<'a>"],
 'crates/engine/src/runtime/binary_object/bytecode_image/encode/plan/module.rs': ["<'a> PlanBuilder<'a>"],
 'crates/engine/src/runtime/binary_object/bytecode_image/model.rs': ['FunctionId',
                                                       'ModuleId',
                                                       'ImageOpaque',
                                                       'ImageValue',
                                                       'ImageInstructionSpan',
                                                       'ImageRelocation',
                                                       'ImageCode',
                                                       'ImageLocalVariable',
                                                       'ImageClosureVariable',
                                                       'ImageFunctionDebug',
                                                       'ImageFunctionEnvelope',
                                                       'FunctionRecord',
                                                       'ModuleRequest',
                                                       'ModuleExport',
                                                       'ModuleImport',
                                                       'ModuleRecord',
                                                       'ImageAtomSummary',
                                                       'BytecodeImage'],
 'crates/engine/src/runtime/binary_object/bytecode_image/native_plan.rs': ["<'image> NativeAtomRef<'image>",
                                                             'NativeLabel',
                                                             "NativeOperands<'_>",
                                                             "<'image> NativeInstruction<'image>",
                                                             "<'image> NativeCodePlan<'image>",
                                                             'NativePlanError',
                                                             'fmt::Display for NativePlanError',
                                                             'std::error::Error for '
                                                             'NativePlanError']}

EXPECTED_FIXTURE_BYTECODE_IMAGE_IMPL_HEADERS = {'crates/engine/src/runtime/binary_object/bytecode_image/model.rs': ['ImageLocalVariable',
                                                       'ImageFunctionEnvelope',
                                                       'BytecodeImage'],
 'crates/engine/src/runtime/binary_object/bytecode_image/native_plan.rs': ["<'image> NativeAtomRef<'image>",
                                                             'NativeLabel',
                                                             "NativeOperands<'_>",
                                                             "<'image> NativeInstruction<'image>",
                                                             "<'image> NativeCodePlan<'image>",
                                                             'NativePlanError',
                                                             'fmt::Display for NativePlanError',
                                                             'std::error::Error for '
                                                             'NativePlanError']}
