[package]
name = "quickjs-oxide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
quickjs-oxide-engine = { workspace = true }
quickjs-oxide-host = { workspace = true }

[features]
default = []
test262-host = ["quickjs-oxide-engine/test262-host"]
